name: Ping Web Site

on:
  push:
    branches: [ master ]
  schedule: 
    - cron: '*/5 * * * *' #every 5 minutes
jobs:
  ping:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Install dependencies
      run: dotnet tool install Web.Ping -g
    - name: Ping alist.52qy.repl.co
      run: Web.Ping --host https://alist.52qy.repl.co
    - name: Ping ytsite.aqingyuan.repl.co
      run: Web.Ping --host https://ytsite.aqingyuan.repl.co
    - name: Ping ping.aqingyuan.repl.co
      run: Web.Ping --host https://ping.aqingyuan.repl.co
    - name: Ping mf.aqingyuan.repl.co
      run: Web.Ping --host https://mf.aqingyuan.repl.co
    - name: Ping raw.aqingyuan.repl.co
      run: Web.Ping --host https://raw.aqingyuan.repl.co
    - name: Ping pan.18sexy.repl.co
      run: Web.Ping --host https://pan.18sexy.repl.co
    - name: Ping alist.52qy.repl.co
      run: Web.Ping --host https://alist.52qy.repl.co
    - name: Ping ytsite.aqingyuan.repl.co
      run: Web.Ping --host https://ytsite.aqingyuan.repl.co
    - name: Ping ping.aqingyuan.repl.co
      run: Web.Ping --host https://ping.aqingyuan.repl.co
    - name: Ping mf.aqingyuan.repl.co
      run: Web.Ping --host https://mf.aqingyuan.repl.co
    - name: Ping raw.aqingyuan.repl.co
      run: Web.Ping --host https://raw.aqingyuan.repl.co
    - name: Ping pan.18sexy.repl.co
      run: Web.Ping --host https://pan.18sexy.repl.co
